# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/
params:
  plugins:
    css:
      - link: "plugins/glightbox/glightbox.css"
      - link: "plugins/swiper/swiper-bundle.css"
    js:
      - link: "plugins/glightbox/glightbox.js"
      - link: "js/gallery-slider.js"
      - link: "plugins/swiper/swiper-bundle.js"
      - link: "js/modal.js"

# Website name
title: 전북대 김선강 
# Website URL
baseURL: 'https://machoganzi.github.io/'

############################
## LANGUAGE
############################

defaultContentLanguage: ko
hasCJKLanguage: true # 한국어 파일 설정
defaultContentLanguageInSubdir: true
removePathAccents: true

languages:
  en:
    languageName: "English"
    weight: 1
  ko:
    languageName: "한국어"
    weight: 2
############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep


