# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Plan
    url: /#papers
    weight: 11
  - name: College-Club
    url: /#talks
    weight: 12
  - name: Blog
    url: /#blog
    weight: 13
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Contact
    url: /contact/
    weight: 40
  - name: Meeting in Person
    parent: Contact
    url: contact_person/
    weight: 10
  - name: Meeting in Online
    parent: Contact
    url: contact/
    weight: 20
