[[params.plugins.css]]
link = "plugins/glightbox/glightbox.css"
[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
[[params.plugins.js]]
link = "js/gallery-slider.js"
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"